### PR TITLE
Added text alignament for the clock

### PR DESCRIPTION
**Pull request by bomdia**
I've added the ability to choose the alignment of the text (useful only for multiline formats)
while i was here i fixed the last 2 thing reported on https://extensions.gnome.org/review/48997 for the review of the version 14, all new code respect the guideline (if they don't chose to change them again...)

### CODE REVIEW

**Comment by KolbyML** [comment]
I am assuming this fixes this issue https://github.com/marcinjakubowski/date-menu-formatter/issues/17

Big fan of this PR if it does

**Comment by KolbyML** [comment]
I tested it and it works I did notice one issue though. This PR adds extra space on each side 
image
Causing my clock to be to far from both of the other things on my dock now

**Comment by KolbyML** [comment]
Here is a picture of my setup on the previous verison 
image
the spacing on the right is less

**Comment by bomdia** [comment]
@KolbyML I've only dynamized the align, before was hardcoded as center and now you can chose between left center and right
So this pr isn't the crux, are you sure to use the same font as before or that some space got in the format string or have you changed theme?

**Comment by KolbyML** [comment]
Yeah I think you are right. Whatever is causing it hopefully it will be fixed in the future

**Comment by KolbyML** [comment]
I fixed the spacing with this
image
image
In case anyone in the future is interesting

**Pull request merged**
