### PR TITLE
Update for GNOME 45

### PR DESCRIPTION
**Pull request by andyholmes**
* [chore: bump shell-version to "45"](https://github.com/marcinjakubowski/date-menu-formatter/commit/075d2b35a279281f33a3e6f9a05786fa57b7ba14)
* [feat: add gettext-domain to metadata.json](https://github.com/marcinjakubowski/date-menu-formatter/commit/1c4d7394fc87f8816efdb0565c1008c03e157051)
* [refactor: use GLib instead of deprecated Mainloop](https://github.com/marcinjakubowski/date-menu-formatter/commit/5a3d1a1bbbd0a95031c3b657c92d75dc2525b19b)
* [refactor: port extension.js to ESModules](https://github.com/marcinjakubowski/date-menu-formatter/commit/5bd4d52815fbf5679942e8ac75757b2444350764)
* [refactor: port prefs.js to ESModules](https://github.com/marcinjakubowski/date-menu-formatter/commit/78c0c4c8ce073f5fc2e72aab86cd57a7678ab875)

### CODE REVIEW

**Comment by andyholmes** [comment]
I tried to touch as little as possible, leaving anything unrelated to the porting process as-is. I also left the version bump to you, but let me know if I missed anything :slightly_smiling_face:

**Comment by ciscorucinski** [comment]
I downloaded the code for the PR and added it to my system (and renamed the folder), but I got an error message.

@andyholmes were you able to get the PR working on your machine? Given that Gnome 45 will not be added anytime in the foreseeable future (https://github.com/marcinjakubowski/date-menu-formatter/issues/26), it might be advisable to create your own fork and upload it so others on Gnome 45 can use this extension

**Comment by andyholmes** [comment]
Yep, it worked for me. Renaming the folder might have caused problems, since the folder name must match the UUID in `metadata.json`. Other than that, an error message would give more clues :slightly_smiling_face:

**Comment by ciscorucinski** [comment]
Yes, I had to rename it to the UUID.

The settings of extension date-menu-formatter@marcinjakubowski.github.com had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by andyholmes** [comment]
Are you sure it's the version here installed? It works for me:

[Screencast from 2023-09-30 16-09-36.webm](https://github.com/marcinjakubowski/date-menu-formatter/assets/1265208/555a5037-b178-41d6-8dbe-a1866b18fe36)

Here's a ZIP:

[date-menu-formatter@marcinjakubowski.github.com.shell-extension.zip](https://github.com/marcinjakubowski/date-menu-formatter/files/12775681/date-menu-formatter%40marcinjakubowski.github.com.shell-extension.zip)

**Comment by ciscorucinski** [comment]
I was getting the same error message after installing using the above zip file. I was just copy-pasting-renaming directories.

I then tried to use `gnome-extensions create -i` and just copy-pasted the files from the zip into the newly created extension directory, and followed some gnome extension creation documentation online to enable and restart. My Extension Application showed there was a new version available and to restart my system. After restarting the system, the extension is working now as expected.

Screenshot from 2023-10-01 18-13-51

**Comment by gamersi** [comment]
it works for me! thanks!

**Comment by queenbiscuit311** [comment]
I couldn't get the `gnome-extensions create -i` to work at first but it would appear that contrary to guides online restarting the shell does not work but restarting the system does. Working great now.

**Comment by ciscorucinski** [comment]
One thing I noticed afterwards is that my system wasn't using Gnome 45, so I was so confused as to why the code was working for an older Gnome version. I was unable to download any older versions before.

But, I guess, when my extensions app said there was a new version, it downloaded an older version as none of the code uses the new import declarations anymore. But I'm confused as to why I wasn't able to download an older version before.

**Comment by lateparty** [comment]
Downloaded the zip from https://github.com/marcinjakubowski/date-menu-formatter/pull/25#issuecomment-1741879140 and confirmed as working for me on Gnome 45.1 and Arch synced to the latest repos.

**Comment by ciro-mota** [comment]
Working normally for me for weeks.
Arch Linux - GNOME 45.

**Comment by queenbiscuit311** [comment]
> Working normally for me for weeks.
> Arch Linux - GNOME 45.

Same here. Had the clock freeze once but that's about it, working perfectly otherwise.

**Pull request merged**
