### PR TITLE
[FEAUTURE] Custom Formatters With timezone and language ability

### PR DESCRIPTION
**Pull request by bomdia**
Added Custom Formatters:

- original: 
  - Original library 
  - support custom language but not custom timezone
- luxon: 
  - Formatter that use Luxon js as library
  - support custom language and custom timezone
- swatch: 
  - Use luxon to provide Swatch beat time format 
  - meaningful example of custom formatter ability

### CODE REVIEW

**Comment by bomdia** [comment]
luxon library format style is similar to original libary format style but there are some differences, so the format string is compatible between the 2 for most cases

**Comment by marcinjakubowski** [comment]
oh that looks nice, thanks so much! let me play a little bit with it first before merging though.

**Comment by bomdia** [comment]
i've added the last bit of code for enabling calendar type chose (work only with luxon formatter as it have that option)

**Comment by marcinjakubowski** [comment]
if you'd like to have this merged still, please update to latest version with gnome 45 support and i'll merge

**Pull request closed without merging**
